### PR TITLE
Hashing login before displaying it in the debug window

### PR DESCRIPTION
**Pull request by Rackover**
Absolutely untested

### CODE REVIEW

**Comment by Geosearchef** [comment]
That makes it entirely useless for debugging.

**Comment by Rackover** [comment]
No.






now if you might want to actually write longer messages so that I can understand your thoughts instead of short and snappy catchphrases, maybe we can start having a constructive discussion.

**Comment by Geosearchef** [comment]
This pull request makes the debug window useless for debugging.

**Comment by Rackover** [comment]
No, it does not. You stil have exactly the same number of informations displayed.

**Comment by Rackover** [comment]
Will you eventually explain why you think it makes it useless for debugging ?

**Comment by Geosearchef** [comment]
Cause you can't distinguish which user is having which problems

**Comment by Rackover** [comment]
Yes you can, hashing the same login will always produce the same result, so you can still tell users apart and in a minute see which user correspond to which hash.
The reason this PR was made is because we received complaints in May of people using the ICE adapter as a mean to discriminate players based on their connection status or to acquire details about them with the debug window (i cant remember which). It was stated as necessary to be done but no one actually showed up to do it, and you angrily asked me to do it myself if I really wanted it to be done.
So I made this PR. The goal is not to scramble user information to no longer be able to debug anything, the goal is to make it harder for the average user to put a name on a network connection.
Now this was 4 months ago so I don't quite remember the full circumstances. But I'm pretty sure this was the idea.

**Comment by Geosearchef** [comment]
As far as I remember it was about people quitting laderr matches during setup due to seeing their opponent. This could be fixed by delaying the display of the login.

Hashing logins is gonna make debugging a lot more hassle as one (me) has to correlate hashes to usernames while also trying to figure out what's going in which leads to errors and adds an additional, unnecessary, layer of complexity.

One shouldn't solve moderation issues by making debugging more difficult.

**Comment by Rackover** [comment]
Display first and last letter of name, hash the rest.

**Pull request closed without merging**
